AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for Lambda functions and S3 bucket
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3bucket-lambda-88889999

  S3BucketsDataAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"

  S3BucketsDataAccessLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: S3BucketsDataAccessLambdaFunction
      Code:
        ZipFile: |
          import json
          import boto3

          def lambda_handler(event, context):

              client = boto3.client('s3')
              bucketList = []
              Buckets = client.list_buckets()["Buckets"]

              for bucket in Buckets:
                  bucketName = bucket["Name"]
                  allObject = []
                  my_objects = client.list_objects_v2( Bucket = bucketName )

                  try:
                      for obj in my_objects["Contents"]:
                          response = client.get_object(Bucket = bucketName, Key = obj["Key"])["Body"].read().decode('utf-8')
                          allObject.append({'name' : obj["Key"], 'content' : response})
                      bucketList.append( {'bucketName':bucketName, 'objects':allObject} )
                  except Exception  as e:
                      bucketList.append({'bucketName':bucketName, 'objects':[]})
                      continue

              data={}
              data['statusCode'] = 200
              data['headers'] = {
                  "Content-Type": "application/json",
                  "Access-Control-Allow-Origin": "*",
                  "Access-Control-Allow-Headers": "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token",
                  "Access-Control-Allow-Methods": "OPTIONS,GET"
                }
              data['body'] = json.dumps(bucketList)
              return data
      Handler: index.lambda_handler
      Role: !GetAtt S3BucketsDataAccessRole.Arn
      Runtime: python3.9
  GetBucketsDataAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: GetBucketsDataAPI
      Description: Example REST API created with CloudFormation
  GetBucketsDataAPIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref GetBucketsDataAPI
      ParentId: !GetAtt GetBucketsDataAPI.RootResourceId
      PathPart: myresource
  MyGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref GetBucketsDataAPIResource
      RestApiId: !Ref GetBucketsDataAPI
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${S3BucketsDataAccessLambdaFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200
  MyDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: MyGetMethod
    Properties:
      RestApiId: !Ref GetBucketsDataAPI
      StageName: Prod
Outputs:
  ApiEndpoint:
    Description: Endpoint URL of the created API
    Value: !Sub "https://${GetBucketsDataAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/myresource"
# This a comment